In [1]:
import pandas as pd
import numpy as np

data = {
    "age": [25, 32, np.nan, 45, 29],
    "salary": [50000, 65000, 70000, np.nan, 52000],
    "city": ["Hyderabad", "Bangalore", "Hyderabad", "Chennai", None],
    "purchased": ["Yes", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

df

    age   salary       city purchased
0  25.0  50000.0  Hyderabad       Yes
1  32.0  65000.0  Bangalore        No
2   NaN  70000.0  Hyderabad       Yes
3  45.0      NaN    Chennai        No
4  29.0  52000.0        NaN       Yes

In [2]:
df.isnull().sum()

age          1
salary       1
city         1
purchased    0
dtype: int64

In [3]:
df["age"] = df["age"].fillna(df["age"].median())
df["salary"] = df["salary"].fillna(df["salary"].median())

In [4]:
df["city"] = df["city"].fillna(df["city"].mode()[0])

In [5]:
df.isnull().sum()

age          0
salary       0
city         0
purchased    0
dtype: int64

In [6]:
encoded_df = pd.get_dummies(
    df,
    columns=["city"],
    drop_first=False
)

encoded_df

    age   salary purchased  city_Bangalore  city_Chennai  city_Hyderabad
0  25.0  50000.0       Yes           False         False            True
1  32.0  65000.0        No            True         False           False
2  30.5  70000.0       Yes           False         False            True
3  45.0  58500.0        No           False          True           False
4  29.0  52000.0       Yes           False         False            True

In [7]:
encoded_df["purchased"] = encoded_df["purchased"].map({
    "No": 0,
    "Yes": 1
})

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

encoded_df[["age", "salary"]] = scaler.fit_transform(
    encoded_df[["age", "salary"]]
)

encoded_df

        age    salary  purchased  city_Bangalore  city_Chennai  city_Hyderabad
0 -1.079145 -1.200699          1           False         False            True
1 -0.044348  0.778475          0            True         False           False
2 -0.266091  1.438200          1           False         False            True
3  1.877417 -0.079167          0           False          True           False
4 -0.487833 -0.936809          1           False         False            True

In [9]:
data = {
    "age": [22, 30, 35, np.nan, 50, 41],
    "income": [30000, 45000, np.nan, 80000, 120000, 75000],
    "city": ["Hyderabad", "Mumbai", "Delhi", "Hyderabad", None, "Delhi"],
    "bought_product": ["No", "Yes", "Yes", "No", "Yes", "Yes"]
}

In [11]:
df = pd.DataFrame(data)
df

    age    income       city bought_product
0  22.0   30000.0  Hyderabad             No
1  30.0   45000.0     Mumbai            Yes
2  35.0       NaN      Delhi            Yes
3   NaN   80000.0  Hyderabad             No
4  50.0  120000.0        NaN            Yes
5  41.0   75000.0      Delhi            Yes

In [12]:
df.isnull().sum()

age               1
income            1
city              1
bought_product    0
dtype: int64

In [14]:
df["age"] = df["age"].fillna(df["age"].median())
df["income"] = df["income"].fillna(df["income"].median())

In [15]:
df["city"] = df["city"].fillna(df["city"].mode()[0])

In [16]:
df.isnull().sum()

age               0
income            0
city              0
bought_product    0
dtype: int64

In [17]:
encoded_df = pd.get_dummies(
    df,
    columns=["city"],
    drop_first=False
)

encoded_df

    age    income bought_product  city_Delhi  city_Hyderabad  city_Mumbai
0  22.0   30000.0             No       False            True        False
1  30.0   45000.0            Yes       False           False         True
2  35.0   75000.0            Yes        True           False        False
3  35.0   80000.0             No       False            True        False
4  50.0  120000.0            Yes        True           False        False
5  41.0   75000.0            Yes        True           False        False

In [18]:
encoded_df["bought_product"] = encoded_df["bought_product"].map({
    "No": 0,
    "Yes": 1
})

In [25]:
from sklearn.model_selection import train_test_split
X = pd.DataFrame(
    encoded_df[["age", "income", "city_Hyderabad", "city_Mumbai", "city_Delhi"]],
    columns=["age", "income", "city_Hyderabad", "city_Mumbai", "city_Delhi"]
)

y = encoded_df["bought_product"]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

encoded_df[["age", "income"]] = scaler.fit_transform(
    encoded_df[["age", "income"]]
)

encoded_df

        age    income  bought_product  city_Delhi  city_Hyderabad  city_Mumbai
0 -1.552819 -1.433141               0       False            True        False
1 -0.632630 -0.906681               1       False           False         True
2 -0.057512  0.146239               1        True           False        False
3 -0.057512  0.321725               0       False            True        False
4  1.667842  1.725618               1        True           False        False
5  0.632630  0.146239               1        True           False        False

In [36]:
X = encoded_df.drop("bought_product", axis=1)
y = encoded_df["bought_product"]

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [39]:
X_train = X_train.copy()
X_test = X_test.copy()

X_train[["age", "income"]] = scaler.fit_transform(
    X_train[["age", "income"]]
)

X_test[["age", "income"]] = scaler.transform(
    X_test[["age", "income"]]
)

In [40]:
print(X_train)

        age    income  city_Delhi  city_Hyderabad  city_Mumbai
5  0.122169 -0.662266        True           False        False
2 -0.855186 -0.662266        True           False        False
4  1.588203  1.721892        True           False        False
3 -0.855186 -0.397360       False            True        False